#!/bin/zsh

if git_status=$(cd $1 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"

  if [[ $git_branch = "release" || $git_branch = "master" ]]; then
    git_branch_format="#[fg=colour7,bg=colour197] ${git_branch}"
  else
    git_branch_format="#[fg=colour7,bg=colour033] ${git_branch}"
  fi
else
  git_branch=""
fi

directory="#[fg=colour0,bg=colour12] NODE #[fg=colour27,bg=colour16] $(node -v) #[fg=colour0,bg=colour12] PATH #[fg=colour27,bg=colour16] $1 $git_branch_format "

echo "$directory$git_info"
